name: archibat2021
description: ARCHIBAT ACADEMY.
version: 1.0.0+0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.3
  nb_utils: ^4.4.4
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.1.0

  # Common
  url_launcher: ^6.0.3
  http: ^0.13.3
  html: ^0.15.0
  package_info: ^2.0.2

  # IMAGES
  cached_network_image: ^3.1.0
  card_swiper: ^1.0.2

  # STATE MANAGEMENT
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

  # WEB TOOLS
  webview_flutter: ^2.0.8

  # ADS
  google_mobile_ads: ^0.12.2

  # UI
  flutter_svg: ^0.22.0
  flutter_slidable: ^0.6.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_staggered_animations: ^1.0.0
  dots_indicator: ^2.0.0
  percent_indicator: ^3.0.1
  carousel_slider: ^4.0.0
  animations: ^2.0.1
  photo_view: ^0.13.0

  # NOTIFICATION
  flutter_local_notifications: ^5.0.0+4
  onesignal_flutter: ^3.2.3

  #Dimond kit
  sleek_circular_slider: ^2.0.0
  sliding_up_panel: ^2.0.0+1

  # Cloud Storage #
  expandable_bottom_sheet: ^1.0.0+2

  collection: ^1.15.0
  diacritic: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:  "^0.9.2"
  mobx_codegen: ^2.0.2
  build_runner: ^2.0.6
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter_icons:
  image_path: "assets/icon/app_logo.jpg"
  android: "launcher_icon"
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/medium/
    - images/archibat/
    - images/cgeci/
    - images/LikeButton/
    - images/LikeButton/image/
    - images/cgeci/svg/
    - images/cgeci/exposants/
    - images/cgeci/info/
    - assets/integrations/lang/
    - assets/shophop_data/
    - images/app/icons/
    - images/app/
    - images/app/ic_rate_app.png
    - assets/medium/mediumhtmlpage.html
    - assets/integrations/map_point.json
    - assets/defaultTheme/
    - assets/cricket_data/

  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

